//! Core event types for the hydra event-sourced system.
//!
//! This module defines the foundational event and error types used
//! throughout the system. All types are self-contained and do not
//! depend on the [`crate::core`] module.
//!
//! - [`TaskId`] — unique identifier for a task
//! - [`SystemEvent`] — all domain events enumerated
//! - [`Error`] — error classification
//! - Per-layer event types — type-level markers for the five
//!   architectural layers

// ---------------------------------------------------------------------------
// TaskId
// ---------------------------------------------------------------------------

/// A unique identifier for a task.
///
/// Wraps a `u64` value. Task IDs uniquely identify a task and
/// correlate events across the system.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TaskId(pub(crate) u64);

impl TaskId {
    /// Create a new `TaskId` from the given raw value.
    ///
    /// Only available in tests because production code should use the
    /// atomic counter in [`execute_task`] to avoid ID collisions.
    #[cfg(test)]
    pub fn new(value: u64) -> Self {
        TaskId(value)
    }
}

impl std::fmt::Display for TaskId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "TaskId({})", self.0)
    }
}

// ---------------------------------------------------------------------------
// SystemEvent
// ---------------------------------------------------------------------------

/// Every state transition, operation, and error in the system is
/// recorded as a [`SystemEvent`].
///
/// All task-referencing variants use a consistent `id: TaskId` field
/// for pattern-matching convenience.
///
/// This enum is `#[non_exhaustive]` to allow adding variants without
/// a breaking change.
// Manual PartialEq: guard against NaN in Evaluation scores so that
// two identical events with NaN score compare as equal.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub enum SystemEvent {
    /// A task has been activated and is ready for execution.
    TaskStarted {
        /// The identifier of the task that started.
        id: TaskId,
    },
    /// The planner decomposed a goal into sub-goals.
    TaskDecomposed {
        /// The identifier of the parent task.
        id: TaskId,
        /// The sub-goals produced by planning.
        sub_goals: Vec<String>,
    },
    /// A single step within a task was completed.
    TaskStepCompleted {
        /// The identifier of the task making progress.
        id: TaskId,
        /// The zero-based step index that was completed.
        step: u32,
    },
    /// A task completed successfully.
    TaskCompleted {
        /// The identifier of the completed task.
        id: TaskId,
        /// A human-readable summary of the result.
        summary: String,
    },
    /// A task failed after exhausting all retry attempts.
    TaskFailed {
        /// The identifier of the failed task.
        id: TaskId,
        /// The error that caused the failure.
        error: Error,
    },
    /// A task is blocked waiting on a sub-task or resource.
    TaskBlocked {
        /// The identifier of the blocked task.
        id: TaskId,
        /// A human-readable reason for the block.
        reason: String,
    },
    /// The context window was compressed to manage token usage.
    ContextCompressed {
        /// The identifier of the task whose context was compressed.
        id: TaskId,
        /// Context size (in tokens or bytes) before compression.
        before_size: u64,
        /// Context size (in tokens or bytes) after compression.
        after_size: u64,
    },
    /// An artifact was produced by a layer.
    ArtifactProduced {
        /// The identifier of the task that produced the artifact.
        id: TaskId,
        /// The name of the layer that produced it (e.g. `"Memory"`).
        layer: &'static str,
        /// The artifact content.
        artifact: String,
    },
    /// A metric evaluation was performed on a task's output.
    Evaluation {
        /// The identifier of the task being evaluated.
        id: TaskId,
        /// The metric name (e.g. `"relevance"`, `"coherence"`).
        metric: String,
        /// The score produced by the evaluation.
        score: f64,
    },
    /// Feedback was generated by the system for self-improvement.
    FeedbackGenerated {
        /// The identifier of the task that triggered the feedback.
        id: TaskId,
        /// The insight or feedback text.
        insight: String,
    },
}

// Manual PartialEq so that Evaluation's f64 score uses to_bits()
// comparison (NaN == NaN) instead of the default f64 equality
// (NaN != NaN). All other variants compare field-by-field as normal.
impl PartialEq for SystemEvent {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (SystemEvent::TaskStarted { id: a }, SystemEvent::TaskStarted { id: b }) => a == b,
            (
                SystemEvent::TaskDecomposed {
                    id: a,
                    sub_goals: b,
                },
                SystemEvent::TaskDecomposed {
                    id: c,
                    sub_goals: d,
                },
            ) => a == c && b == d,
            (
                SystemEvent::TaskStepCompleted { id: a, step: b },
                SystemEvent::TaskStepCompleted { id: c, step: d },
            ) => a == c && b == d,
            (
                SystemEvent::TaskCompleted { id: a, summary: b },
                SystemEvent::TaskCompleted { id: c, summary: d },
            ) => a == c && b == d,
            (
                SystemEvent::TaskFailed { id: a, error: b },
                SystemEvent::TaskFailed { id: c, error: d },
            ) => a == c && b == d,
            (
                SystemEvent::TaskBlocked { id: a, reason: b },
                SystemEvent::TaskBlocked { id: c, reason: d },
            ) => a == c && b == d,
            (
                SystemEvent::ContextCompressed {
                    id: a,
                    before_size: b,
                    after_size: c,
                },
                SystemEvent::ContextCompressed {
                    id: d,
                    before_size: e,
                    after_size: f,
                },
            ) => a == d && b == e && c == f,
            (
                SystemEvent::ArtifactProduced {
                    id: a,
                    layer: b,
                    artifact: c,
                },
                SystemEvent::ArtifactProduced {
                    id: d,
                    layer: e,
                    artifact: f,
                },
            ) => a == d && b == e && c == f,
            (
                SystemEvent::Evaluation {
                    id: a,
                    metric: b,
                    score: c,
                },
                SystemEvent::Evaluation {
                    id: d,
                    metric: e,
                    score: f,
                },
            ) => a == d && b == e && c.to_bits() == f.to_bits(),
            (
                SystemEvent::FeedbackGenerated { id: a, insight: b },
                SystemEvent::FeedbackGenerated { id: c, insight: d },
            ) => a == c && b == d,
            _ => false,
        }
    }
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

/// Error classification for the hydra system.
///
/// Errors are divided into three severity levels plus a recursive
/// variant for wrapping child-task failures.
///
/// This enum is `#[non_exhaustive]` to allow adding variants without
/// a breaking change.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub enum Error {
    /// A transient, retryable failure (e.g. network timeout, rate
    /// limit).
    Transient(String),
    /// An operation exceeded its allowed time limit.
    Timeout(String),
    /// A non-retryable, fatal failure (e.g. invalid configuration,
    /// invariant violation).
    Fatal(String),
    /// A task failed because a sub-task it depends on failed.
    TaskFailed {
        /// The identifier of the task whose failure caused this error.
        id: TaskId,
        /// The wrapped child error.
        cause: Box<Error>,
    },
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Transient(msg) => write!(f, "transient: {msg}"),
            Error::Timeout(msg) => write!(f, "timeout: {msg}"),
            Error::Fatal(msg) => write!(f, "fatal: {msg}"),
            Error::TaskFailed { id, cause } => {
                write!(f, "task {id} failed: {cause}")
            }
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Error::TaskFailed { cause, .. } => Some(cause.as_ref()),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Per-layer event types (defined via macro for single-source doc)
// ---------------------------------------------------------------------------

macro_rules! define_layer_event {
    ($name:ident, $description:literal) => {
        #[doc = concat!("Event type for the ", $description, " layer.")]
        #[doc = concat!($description, " events correspond to layer-specific operations.")]
        ///
        /// NOTE: This type derives `Copy`. If fields are added later,
        /// ensure they are also `Copy` or remove the `Copy` derive.
        #[derive(Debug, Clone, Copy)]
        pub struct $name;
    };
}

define_layer_event!(OrchestrationEvent, "Orchestration");
define_layer_event!(RetrievalEvent, "Retrieval");
define_layer_event!(MemoryEvent, "Memory");
define_layer_event!(ContextEvent, "Context");
define_layer_event!(ExecutionEvent, "Execution");

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::hash_map::DefaultHasher;
    use std::hash::Hash;
    use std::hash::Hasher;

    // -- SystemEvent construction -------------------------------------------

    /// Verify that every [`SystemEvent`] variant is constructible with
    /// all payload fields.
    #[test]
    fn system_event_task_started() {
        let event = SystemEvent::TaskStarted { id: TaskId(1) };
        assert!(matches!(event, SystemEvent::TaskStarted { id: TaskId(1) }));
    }

    #[test]
    fn system_event_task_decomposed() {
        let event = SystemEvent::TaskDecomposed {
            id: TaskId(2),
            sub_goals: vec!["goal-a".into(), "goal-b".into()],
        };
        assert!(matches!(
            event,
            SystemEvent::TaskDecomposed { id: TaskId(2), .. }
        ));
    }

    #[test]
    fn system_event_task_step_completed() {
        let event = SystemEvent::TaskStepCompleted {
            id: TaskId(3),
            step: 5,
        };
        assert!(matches!(
            event,
            SystemEvent::TaskStepCompleted {
                id: TaskId(3),
                step: 5,
            }
        ));
    }

    #[test]
    fn system_event_task_completed() {
        let event = SystemEvent::TaskCompleted {
            id: TaskId(4),
            summary: "done".into(),
        };
        assert!(matches!(
            event,
            SystemEvent::TaskCompleted { id: TaskId(4), .. }
        ));
    }

    #[test]
    fn system_event_task_failed() {
        let event = SystemEvent::TaskFailed {
            id: TaskId(5),
            error: Error::Transient("oops".into()),
        };
        assert!(matches!(
            event,
            SystemEvent::TaskFailed { id: TaskId(5), .. }
        ));
    }

    #[test]
    fn system_event_task_blocked() {
        let event = SystemEvent::TaskBlocked {
            id: TaskId(6),
            reason: "waiting for input".into(),
        };
        assert!(matches!(
            event,
            SystemEvent::TaskBlocked { id: TaskId(6), .. }
        ));
    }

    #[test]
    fn system_event_context_compressed() {
        let event = SystemEvent::ContextCompressed {
            id: TaskId(7),
            before_size: 1000,
            after_size: 500,
        };
        assert!(matches!(
            event,
            SystemEvent::ContextCompressed {
                id: TaskId(7),
                before_size: 1000,
                after_size: 500,
            }
        ));
    }

    #[test]
    fn system_event_artifact_produced() {
        let event = SystemEvent::ArtifactProduced {
            id: TaskId(8),
            layer: "Memory",
            artifact: "data".into(),
        };
        assert!(matches!(
            event,
            SystemEvent::ArtifactProduced {
                id: TaskId(8),
                layer: "Memory",
                ..
            }
        ));
    }

    #[test]
    fn system_event_evaluation() {
        let event = SystemEvent::Evaluation {
            id: TaskId(9),
            metric: "relevance".into(),
            score: 0.95,
        };
        assert!(matches!(
            event,
            SystemEvent::Evaluation {
                id: TaskId(9),
                metric,
                score: 0.95,
            } if metric == "relevance"
        ));
    }

    #[test]
    fn system_event_feedback_generated() {
        let event = SystemEvent::FeedbackGenerated {
            id: TaskId(10),
            insight: "improve prompt".into(),
        };
        assert!(matches!(
            event,
            SystemEvent::FeedbackGenerated { id: TaskId(10), .. }
        ));
    }

    // -- Error construction --------------------------------------------------

    /// Verify that every [`Error`] variant is constructible with its
    /// specified payload shape.
    #[test]
    fn error_transient_constructible() {
        let err = Error::Transient("retry".into());
        assert!(matches!(err, Error::Transient(ref msg) if msg == "retry"));
    }

    #[test]
    fn error_timeout_constructible() {
        let err = Error::Timeout("took too long".into());
        assert!(matches!(err, Error::Timeout(ref msg) if msg == "took too long"));
    }

    #[test]
    fn error_fatal_constructible() {
        let err = Error::Fatal("corrupt state".into());
        assert!(matches!(err, Error::Fatal(ref msg) if msg == "corrupt state"));
    }

    #[test]
    fn error_task_failed_constructible() {
        let inner = Error::Transient("inner".into());
        let err = Error::TaskFailed {
            id: TaskId(1),
            cause: Box::new(inner),
        };
        assert!(matches!(err, Error::TaskFailed { id: TaskId(1), .. }));
    }

    // -- Per-layer event type construction -----------------------------------

    /// Verify that every per-layer event type is constructible.
    #[test]
    fn layer_event_types_are_constructible() {
        let _ = OrchestrationEvent;
        let _ = RetrievalEvent;
        let _ = MemoryEvent;
        let _ = ContextEvent;
        let _ = ExecutionEvent;
    }

    // -- Debug bounds --------------------------------------------------------

    /// Verify that all event types implement [`Debug`].
    #[test]
    fn system_event_is_debug() {
        fn assert_debug<T: std::fmt::Debug>() {}
        assert_debug::<SystemEvent>();
    }

    #[test]
    fn error_is_debug() {
        fn assert_debug<T: std::fmt::Debug>() {}
        assert_debug::<Error>();
    }

    #[test]
    fn task_id_is_debug() {
        fn assert_debug<T: std::fmt::Debug>() {}
        assert_debug::<TaskId>();
    }

    #[test]
    fn layer_event_types_are_debug() {
        fn assert_debug<T: std::fmt::Debug>() {}
        assert_debug::<OrchestrationEvent>();
        assert_debug::<RetrievalEvent>();
        assert_debug::<MemoryEvent>();
        assert_debug::<ContextEvent>();
        assert_debug::<ExecutionEvent>();
    }

    // -- Clone ---------------------------------------------------------------

    /// Verify that all event types implement [`Clone`].
    #[test]
    fn system_event_is_clone() {
        fn assert_clone<T: Clone>() {}
        assert_clone::<SystemEvent>();
    }

    #[test]
    fn error_is_clone() {
        fn assert_clone<T: Clone>() {}
        assert_clone::<Error>();
    }

    #[test]
    fn task_id_is_clone() {
        fn assert_clone<T: Clone>() {}
        assert_clone::<TaskId>();
    }

    #[test]
    fn layer_event_types_are_clone() {
        fn assert_clone<T: Clone>() {}
        assert_clone::<OrchestrationEvent>();
        assert_clone::<RetrievalEvent>();
        assert_clone::<MemoryEvent>();
        assert_clone::<ContextEvent>();
        assert_clone::<ExecutionEvent>();
    }

    /// Verify that [`Error`] clones correctly at runtime, including its
    /// heap-allocated recursive variant.
    #[test]
    fn error_clone_runtime() {
        let inner = Error::Transient("inner".into());
        let err = Error::TaskFailed {
            id: TaskId(1),
            cause: Box::new(inner),
        };
        let cloned = err.clone();
        match &cloned {
            Error::TaskFailed {
                id: TaskId(1),
                cause,
            } => {
                assert!(
                    matches!(cause.as_ref(), Error::Transient(msg) if msg == "inner"),
                    "deep clone: inner cause was not copied correctly",
                );
            }
            other => panic!("expected Error::TaskFailed, got {other:?}"),
        }
    }

    // -- TaskId round-trip ---------------------------------------------------

    /// Verify that [`TaskId`] round-trips correctly through its inner
    /// `u64`.
    #[test]
    fn task_id_round_trip() {
        let original = TaskId(42);
        let extracted = original.0;
        let reconstructed = TaskId(extracted);
        assert_eq!(original, reconstructed);
    }

    #[test]
    fn task_id_hash_consistency() {
        let a = TaskId(1);
        let b = TaskId(1);
        let mut hasher = DefaultHasher::new();
        a.hash(&mut hasher);
        let hash_a = hasher.finish();
        let mut hasher = DefaultHasher::new();
        b.hash(&mut hasher);
        let hash_b = hasher.finish();
        assert_eq!(hash_a, hash_b, "equal TaskIds must produce equal hashes");
    }
}
